export type ShopId = number;

export interface ShopDetails {
  readonly id: ShopId;
  readonly name: string;
}

/**
 * Index of Neopets shop details
 */
export const Shops: Array<ShopDetails> = [
  { id: 1, name: "Neopian Fresh Foods" },
  { id: 2, name: "Kauvara's Magic Shop" },
  { id: 3, name: "Toy Shop" },
  { id: 4, name: "Unis Clothing Shop" },
  { id: 5, name: "Grooming Parlour" },
  // { id: 6, name: " Unk 1" },
  { id: 7, name: "Magical Bookshop" },
  { id: 8, name: "Collectable Card Shop" },
  { id: 9, name: "Battle Magic" },
  { id: 10, name: "Defence Magic" },
  // { id: 11, name: " Unk 2" },
  { id: 12, name: "Neopian Garden Centre" },
  { id: 13, name: "Neopian Pharmacy" },
  { id: 14, name: "Chocolate Factory" },
  { id: 15, name: "The Bakery" },
  { id: 16, name: "Neopian Health Foods" },
  { id: 17, name: "Neopian Gift Shop" },
  { id: 18, name: "Smoothie Store" },
  // { id: 19, name: " Unk 3" },
  { id: 20, name: "Tropical Food Shop" },
  { id: 21, name: "Tiki Tack" },
  { id: 22, name: "Grundos Cafe" },
  { id: 23, name: "Space Weaponry" },
  { id: 24, name: "Space Armour" },
  { id: 25, name: "The Neopian Petpet Shop" },
  { id: 26, name: "The Robo-Petpet Shop" },
  { id: 27, name: "The Rock Pool" },
  // { id: 28, name: " Unk 4" },
  // { id: 29, name: " Unk 5" },
  { id: 30, name: "Spooky Food" },
  { id: 31, name: "Spooky Petpets" },
  // { id: 32, name: " Unk 6" },
  // { id: 33, name: " Unk 7" },
  { id: 34, name: "The Coffee Cave" },
  { id: 35, name: "Slushie Shop" },
  { id: 36, name: "Ice Crystal Shop" },
  { id: 37, name: "Super Happy Icy Fun Snow Shop" },
  { id: 38, name: "Faerieland Bookshop" },
  { id: 39, name: "Faerieland Foods" },
  { id: 40, name: "Faerieland Petpets" },
  { id: 41, name: "Neopian Furniture" },
  { id: 42, name: "Tyrannian Foods" },
  { id: 43, name: "Tyrannian Furniture" },
  { id: 44, name: "Tyrannian Petpets" },
  { id: 45, name: "Tyrannian Weaponry" },
  { id: 46, name: "Hubert's Hotdogs" },
  { id: 47, name: "Pizzaroo" },
  { id: 48, name: "Usukiland" },
  { id: 49, name: "Lost Desert Foods" },
  { id: 50, name: "Peopatras Petpets" },
  { id: 51, name: "Suteks Scrolls" },
  // { id: 52, name: " Unk 8" },
  { id: 53, name: "Neopian School Supplies" },
  { id: 54, name: "Sakhmet Battle Supplies" },
  { id: 55, name: "Osiris Pottery" },
  { id: 56, name: "Merifoods" },
  { id: 57, name: "Ye Olde Petpets" },
  { id: 58, name: "Neopian Post Office" },
  { id: 59, name: "Haunted Weaponry" },
  { id: 60, name: "Spooky Furniture" },
  { id: 61, name: "Wintery Petpets" },
  { id: 62, name: "Jelly Foods" },
  { id: 63, name: "Shops 1" }, // Disney Theatre
  // { id: 64, name: " Unk 9" },
  // { id: 65, name: " Unk 10" },
  { id: 66, name: "Kiko Lake Treats" },
  { id: 67, name: "Kiko Lake Carpentry" },
  { id: 68, name: "Collectable Coins" },
  { id: 69, name: "Petpet Supplies" },
  { id: 70, name: "Booktastic Books" },
  { id: 71, name: "Kreludan Homes" },
  { id: 72, name: "Cafe Kreludor" },
  { id: 73, name: "Kayla's Potion Shop" },
  { id: 74, name: "Darigan Toys" },
  { id: 75, name: "Faerie Furniture" },
  { id: 76, name: "Roo Island Souvenirs" },
  { id: 77, name: "Brightvale Books" },
  { id: 78, name: "The Scrollery" },
  { id: 79, name: "Brightvale Glaziers" },
  { id: 80, name: "Brightvale Armoury" },
  { id: 81, name: "Brightvale Fruits" },
  { id: 82, name: "Brightvale Motery" },
  { id: 83, name: "Royal Potionery" },
  { id: 84, name: "Neopian Music Shop" },
  { id: 85, name: "Lost Desert Medicine" },
  { id: 86, name: "Collectable Sea Shells" },
  { id: 87, name: "Maractite Marvels" },
  { id: 88, name: "Maraquan Petpets" },
  { id: 89, name: "Geraptiku Petpets" },
  { id: 90, name: "Qasalan Delights" },
  { id: 91, name: "Desert Arms" },
  { id: 92, name: "Words OF Antiquity" },
  { id: 93, name: "Faerie Weapon Shop" },
  { id: 94, name: "Illustrious Armoury" },
  { id: 95, name: "Exquisite Ambrosia" },
  { id: 96, name: "Magical Marvels" },
  { id: 97, name: "Legendary Petpets" },
  { id: 98, name: "Plushie Palace" },
  // { id: 99, name: " Unk 11" },
  { id: 100, name: "Wonderous Weaponry" },
  { id: 101, name: "Exotic Foods" },
  { id: 102, name: "Remarkable Restoratives" },
  { id: 103, name: "Fanciful Fauna" },
  { id: 104, name: "Chesterdrawers Antiques" },
  { id: 105, name: "The Crumpetmonger" },
  { id: 106, name: "Neovian Printing Press" },
  { id: 107, name: "Prigpant's & Swolthy Tailors" },
  { id: 108, name: "Mystical Surroundings" },
  // { id: 109, name: " Unk 12" },
  { id: 110, name: "Lampwyck's Lights Fantastic" },
  { id: 111, name: "Cog's Togs" },
  { id: 112, name: "Molten Morsels" },
  { id: 113, name: "Moltaran Petpets" },
  { id: 114, name: "Moltaran Books" },
  // { id: 115, name: " Unk 13" },
  { id: 116, name: "Springy Things" },
  { id: 117, name: "Shops 2" }, // Ugga Shinies
];